### ISSUE TITLE
Team 106 - The Kingsnakes review

### ISSUE THREAD

**Issue by chelmerrox** [krys2fa/tv-show-guide#1]
Hey Chris! 😃 Great presentation (and thank you for presenting too)! You've really done well in your project. 

Review:
- You've got your UI to work on a little bit more although it's not so bad at all.
- Nice work on narrowing your TV shows to shows about cars. 👌

All the best with this project! You're doing well so far! 💯

**Comment by krys2fa** [comment]
Thanks, team.
